name: Test

on: [push]
jobs:
  check-bats-version:
    # where it runs:
    runs-on: ubuntu-latest
    # what we do:
    steps:
      # download repository
      - uses: actions/checkout@v3
      # setup java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # run tests
      - run: ./gradlew clean test
